version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          command: |
            go get -u ./...
            go test ./... -coverprofile=coverage.out
