version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/bcbpio/member-service
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          command: |
            go get -u ./...
            go test ./... -coverprofile=coverage.out
